 # config.yml for PPP (static)

elmin: 10.0 # minimum elevation [deg]
atxfile: '../data/antex/igs20.atx' # ANTEX file

nav:
    monlevel: 1
    pmode: 0 # positioning mode 0:static, 1:kinematic
    csmooth: False # carrier smoothing is enabled
    ephopt: 2 # SSR-APC
    trop_opt: 1
    iono_opt: 1
    phw_opt: 1
    trop_model: 'SAAST'
    iono_model: 'KLOBUCHAR'
    
    eratio: [50.0, 50.0]
    err: [0, 0.007, 0.0035]
    
    # initial value of covariance
    sig_p0: 100.0 # [m]
    sig_v0: 1.0 # [m/s]
    sig_ztd0: 0.1 # [m]
    sig_ion0: 10.0 # [m]
    sig_n0: 30.0 # [cyc]
    
    # Process noise sigma
    # sig_qp: 100.0
    sig_qp: 0.01 # [m/sqrt(s)]
    sig_qv: 1.0 # [m]
    sig_qztd: 0.0008 # [m]
    sig_qion: 10.0 # [m]
    sig_qb: 0.0001  # [m]

    # AR parameters
    armode: 0 # 0:float-ppp,1:continuous,2:instantaneous,3:fix-and-hold
    thresar: 3.0  # AR acceptance threshold
    elmaskar: 15.0

    parmode: 1 # Partial AR 1: normal, 2: PAR
    par_P0: 0.995  # probability of sussefull AR

cs:
    monlevel: 1

